project_id = "yntqxpvmswpdviwwlsyy"

[functions.parse-pdf]
verify_jwt = false

[functions.suggest-metrics]
verify_jwt = false

[functions.extract-plan-items]
verify_jwt = false

[functions.extract-plan-vision]
verify_jwt = false

[functions.lookup-organization]
verify_jwt = false